### ISSUE TITLE
Inline styles without any attributes cause an AssertionError

### ISSUE THREAD

**Issue by alexwlchan** [alexwlchan/html-archiver#4]
Minimal test case:

```python
from html_archiver import HTMLArchiver

html_string = '''
<html>
<head>
<style>
p { color: purple; }
</style>
</head>
</html>
'''

processed = HTMLArchiver().archive_html(html_string, base_url='http://example.org')
```

Throws the following error:

```
Traceback (most recent call last):
  File "demo.py", line 19, in <module>
    processed = HTMLArchiver().archive_html(html_string, base_url='http://example.org')
  File "/Users/alexwlchan/repos/html-inliner/html_archiver.py", line 75, in archive_html
    base_url=base_url)
  File "/Users/alexwlchan/repos/html-inliner/html_archiver.py", line 165, in _archive_style_tags
    assert match is not None, orig_css_string
AssertionError:
p { color: purple; }
```

**Comment by alexwlchan** [comment]
Same test case reveals a second bug: we’re unnecessarily mutating this CSS. Output is as follows:

```html
<html>
<head><meta charset="utf-8">
<style>

p { color: purple; }

</style>
</head>
</html>
```
