### ISSUE TITLE
<style> tags are still quite broken

### ISSUE THREAD

**Issue by alexwlchan** [alexwlchan/html-archiver#8]
Consider the following example:

```python
from html_archiver import HTMLArchiver

a = HTMLArchiver()
print(a.archive_html('''
<head>
<meta charset="utf-8">
<style foo="bar">
div { background: url(https://pbs.twimg.com/profile_images/737359467742912512/t_pzvyZZ_400x400.jpg); }
</style>
</head>
''', base_url=None))
```

```
Traceback (most recent call last):
  File "foo.py", line 11, in <module>
    ''', base_url=None))
  File "/Users/alexwlchan/repos/html-inliner/html_archiver.py", line 79, in archive_html
    base_url=base_url)
  File "/Users/alexwlchan/repos/html-inliner/html_archiver.py", line 170, in _archive_style_tags
    assert match is not None, orig_css_string
AssertionError:
div { background: url(https://pbs.twimg.com/profile_images/737359467742912512/t_pzvyZZ_400x400.jpg); }
```

Looks like I’ve put a `.strip()` in the wrong place.

**Comment by alexwlchan** [comment]
Additionally, if you load the same binary resource more than once, you get empty data for the second. e.g.

```css
div { background: url('rainbow.png'); }
div { background: url('rainbow.png'); }
```

will produce

```css
div { background: url('data:image/png;base64,ABCD...')
div { background: url('data:image/png;base64,')
```

**Comment by alexwlchan** [comment]
Related to #9: we assume that `<style>` tags are non-empty. This is a bad assumption!
